name: Connect to Vault to gather secrets
on: workflow_dispatch
permissions:
    id-token: write
    contents: read
jobs:
    ConnectToVault:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repostory
              uses: actions/checkout@v3

            - name: Install Vault CLI
              run: |
                export VAULT_ADDR="http://ec2-23-22-230-111.compute-1.amazonaws.com:8200"
                echo $VAULT_ADDR
                unzip vault.zip && sudo mv vault /usr/local/bin/
                vault -v
                curl -I $VAULT_ADDR/v1/sys/health # Check if Vault is reachable and health
            
            - name: authenticate to Vault using JWT
              id: vault_auth
              run: |
                export VAULT_ADDR="http://ec2-23-22-230-111.compute-1.amazonaws.com:8200"
                echo $VAULT_ADDR
                if [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ] || [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
                  echo "Required GitHub Actions OIDC environment variables are not set."
                  exit 1
                fi
                jwt_token=$(curl -s $ACTIONS_ID_TOKEN_REQUEST_URL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
                vault login -method=jwt role="cbu_jwt_role" jwt="$jwt_token"

            - name: Authenticate to Vault using Vault Action
              id: vault_jwt_auth
              uses: hashicorp/vault-action@v3
              with:
                url: "http://ec2-23-22-230-111.compute-1.amazonaws.com:8200"
                method: jwt
                role: cbu_jwt_role
                secrets: |
                  kv/data/aabk/dev/pipeline/sp password | PASSWORD;
                  kv/data/aabk/dev/pipeline/sp username | USERNAME;


                #  export VAULT_ADDR="http://ec2-34-228-142-60.compute-1.amazonaws.com:8200"
                #  jwt_token=$(curl -s $ACTIONS_ID_TOKEN_REQUEST_URL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
                #  vault login -method=jwt -path=jwt/ role="get-azure-creds-role" jwt="$jwt_token"

            - name: Read Dynamic Azure SP credentials
              run: |
                echo "Username: ${{ steps.vault_jwt_auth.outputs.USERNAME }}"
                echo "Password: ${{ steps.vault_jwt_auth.outputs.PASSWORD }}"
                echo "Vault authentication successful and secrets retrieved."
              
