name: Connect to Vault to gather secrets
on: workflow_dispatch
jobs:
    ConnectToVault:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repostory
              uses: actions/checkout@v3

            - name: Install Vault CLI
              run: |
                sudo apt-get install -y unzip
                curl -sLo vault.zip https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_amd64.zip
                unzip vault.zip && sudo mv vault /usr/local/bin/
                vault -v
                export VAULT_ADDR="http://ec2-34-228-142-60.compute-1.amazonaws.com:8200"

            - name: Authenticate to Vault (simpler)
              id: vault_jwt_auth
              run: |
                 export VAULT_ADDR="http://ec2-34-228-142-60.compute-1.amazonaws.com:8200"
                 jwt_token=$(curl -s $ACTIONS_ID_TOKEN_REQUEST_URL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
                 vault login -method=jwt role="get-azure-creds-role" jwt="$jwt_token"

            - name: Read Dynamic Azure SP credentials
              run: |
                 vault read -format=json azure/creds/azure_role_resource_deploy > azure_creds.json
                 cat azure_creds.json
              
